name: 'action/to-uppercase'
description: 'upper case a sentence'
inputs:
  text:
    description: 'to-uppercase'
    required: true
    default: 'Hello devOps Nornes, Go Cow Yourself'

branding:
  icon: chevron-down
  color: gray-dark

outputs:
  text:
    description: 'to-uppercase'
    value: ${{ steps.upper-step.outputs.text }}

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Start to upper text ${{ inputs.text }}
      run: |
        upper.sh 'text=${{ inputs.text }}' >> $GITHUB_OUTPUT
      shell: bash
      id: upper-step